version: '3.3'
services:
  app:
    container_name: app
    networks:
      - nodeapp-network
    depends_on: 
      - mongodb
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    networks:
      - nodeapp-network
    image: mongo
    volumes:
      - ./data:/data/db
networks:
  nodeapp-network:
    driver: bridge